server:
  servlet:
    context-path: /trafigura
    session:
      timeout: 3000
      cookie:
        max-age: 3000
  tomcat:
    uri-encoding: UTF-8
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trafigura?serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
          min-idle: 5
          initial-size: 5
          max-total: 5
          max-wait-millis: 200
          type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 192.168.42.103
    port: 6379
    password: 1234
    timeout: 5000
    pool:
      maxActive: 8  # 连接池最大连接数（使用负值表示没有限制）
      maxWait: 800 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      maxIdle: 10 # 连接池中的最大空闲连接
      minIdle: 2 # 连接池中的最小空闲连接
      maxTotal: 10000

mybatis: #mybatis相关配置
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.trafigura.equity.position.entity

devtools: #热部署相关模块
  restart:
    enabled: true  #设置开启热部署
    additional-paths: src/main/java #重启目录
    exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

thymeleaf: #html显示支持插件(若使用)
  cache: false

logging: #mybatis log 控制台打印
  file: application.log
  path: .
  level:
    root: info
    com.trafigura.equity.position.dao: debug